print("Hello! Python!")
print("")
print("Do you know the way?")
print("")
print("Do you don't know the way")
print("")
print("You can to pay, with you life")
print("")
print("come on brother!!!")
print("")
print("da wae!")
print("")
print("da wae!")
print("")
print("da wae!")